### ISSUE TITLE
Gate/Track Information

### ISSUE THREAD

**Issue by ryanamannion** [pieromqwerty/Piero-Amtrak-Train-Tracker#3]
Any idea if it is possible to get gate/track information certain trains at a given station? For example, when the departures board shows that my train is coming in at Gate E, I'll eventually get a push notification through the Amtrak app that tells me where my train is. I'd like to track that information in some other way than sitting at the station for a while lol

Great work on this by the way!

**Comment by piemadd** [comment]
In theory this would be possible to get but not through the API I'm using. Let me look into this.

**Comment by piemadd** [comment]
Yeah TMI there's no way I can reliably get gate information from Amtrak without being super jank. Closing this until someone can find a way to get such information.
